# Generated by Django 5.0.6 on 2024-07-10 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='idCategoria', primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='idProducto', primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('img_producto', models.ImageField(null=True, upload_to='IMG')),
                ('descripcion', models.TextField()),
                ('categoria', models.ForeignKey(db_column='idCategoria', on_delete=django.db.models.deletion.CASCADE, to='Proyecto.categoria')),
            ],
        ),
    ]
