# Generated by Django 5.0.6 on 2024-07-10 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0002_categoria_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(db_column='idCargo', primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_cargo',
            field=models.ForeignKey(db_column='IdCargo', default=1, on_delete=django.db.models.deletion.CASCADE, to='Proyecto.cargo'),
            preserve_default=False,
        ),
    ]
