# Generated by Django 5.0.6 on 2024-07-10 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0003_cargo_usuario_id_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id_cargo',
        ),
    ]
