# Generated by Django 5.0.6 on 2024-07-10 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0004_remove_usuario_id_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='id_cargo',
            field=models.ForeignKey(db_column='idCargo', default=1, on_delete=django.db.models.deletion.CASCADE, to='Proyecto.cargo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cargo',
            name='id_cargo',
            field=models.AutoField(db_column='idcargo', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre_categoria',
            field=models.CharField(max_length=50),
        ),
    ]
