# Generated by Django 5.0.6 on 2024-07-11 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0005_usuario_id_cargo_alter_cargo_id_cargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id_cargo',
        ),
        migrations.AlterField(
            model_name='cargo',
            name='id_cargo',
            field=models.AutoField(db_column='idCargo', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='img_producto',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField()),
                ('id_cargo', models.ForeignKey(db_column='IDCargo', on_delete=django.db.models.deletion.CASCADE, to='Proyecto.cargo')),
                ('id_genero', models.ForeignKey(db_column='IDGenero', on_delete=django.db.models.deletion.CASCADE, to='Proyecto.genero')),
            ],
        ),
    ]
