# Generated by Django 5.0.4 on 2024-05-01 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferremapp', '0002_producto_preciohistorico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio_actual',
            new_name='valor',
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
