# Generated by Django 5.0.4 on 2024-05-01 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferremapp', '0003_rename_precio_actual_producto_valor_producto_fecha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrecioHistorico',
        ),
    ]
