from ProyectoDjango.urls import path
from Proyecto import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.menu, name="menu"),
    path("EPP", views.EPP, name="EPP"),
    path("antiparra", views.antiparra, name="antiparra"),
    path("guantes", views.guantes, name="guantes"),
    path("mascara", views.mascara, name="mascara"),
    path("protector", views.protector, name="protector"),
    path("zapatos", views.zapatos, name="zapatos"),
    path("atornillador", views.atornillador, name="atornillador"),
    path("martillo", views.martillo, name="martillo"),
    path("llave_francesa", views.llave_francesa, name="llave_francesa"),
    path("ator_inalambrico", views.ator_inalambrico, name="ator_inalambrico"),
    path("lijadora", views.lijadora, name="lijadora"),
    path("taladro", views.taladro, name="taladro"),
    path("sierra_circular", views.sierra_circular, name="sierra_circular"),
    path("pintura", views.pintura, name="pintura"),
    path("cemento", views.cemento, name="cemento"),
    path("agorex", views.agorex, name="agorex"),
    path("ladrillo", views.ladrillo, name="ladrillo"),
    path("saco_arena", views.saco_arena, name="saco_arena"),
    path("barnis", views.barnis, name="barnis"),
    path("ceramica", views.ceramica, name="ceramica"),
    path("login", views.conectar, name="login"),
    path("registro", views.registro, name="registro"),
    path("acercade", views.acercade, name="acercade"),
    path("carrito", views.carrito, name="carrito"),
    path("contacto", views.contacto, name="contacto"),
    path("herramientas", views.herramientas, name="herramientas"),
    path("materiales", views.materiales, name="materiales"),
    path("pintura", views.pintura, name="pintura"),
    path("piso", views.piso, name="piso"),
    path("crud", views.crud, name="crud"),
    path("empleado_add", views.empleado_add, name="empleado_add"),
    path("user_update", views.user_update, name="user_update"),
    path("user_del/<str:pk>", views.user_del, name="user_del"),
    path("user_findEdit/<str:pk>", views.user_findEdit, name="user_findEdit"),
    path("logout", views.desconectar, name="logout"),
    path("catalogo", views.catalogo, name="catalogo"),
    path("producto_add", views.producto_add, name="producto_add"),
    path("producto_mod", views.producto_mod, name="producto_mod"),
    path("productoedit/<str:pk>", views.productoedit, name="productoedit"),
    path("producto_del/<str:pk>", views.producto_del, name="producto_del"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)