from django.test import LiveServerTestCase
from selenium import webdriver
from selenium.webdriver.common.by import By
import time

# Create your tests here.

class TestFerremas(LiveServerTestCase):
    def setUp(self):
        self.selenium = webdriver.Chrome()
        self.selenium.maximize_window()
        super().setUp()
    
    def tearDown(self):
        self.selenium.quit()
        super().tearDown()

    def test_g01(self):

        # Caso de prueba para probar el inicio de sesión del usuario administrador

        self.selenium.get("http://localhost:8000/")
        time.sleep(1)
        self.selenium.find_element(By.ID, "id_username").click()
        time.sleep(1)
        self.selenium.find_element(By.ID, "id_username").send_keys("asdasd")
        time.sleep(1)
        self.selenium.find_element(By.ID, "id_password").click()
        time.sleep(1)
        self.selenium.find_element(By.ID, "id_password").send_keys("Medrano00!")
        time.sleep(1)
        self.selenium.find_element(By.XPATH, "/html/body/div/div/div/div/div/div/div/form/input[2]").click()
        time.sleep(5)

    def test_g02(self):

        # Caso de prueba para probar integración de Transbank - Opción Aceptar

        self.selenium.get("http://localhost:8000/")
        time.sleep(1)
        self.selenium.find_element(By.ID, "id_username").click()
        time.sleep(1)
        self.selenium.find_element(By.ID, "id_username").send_keys("asdasd")
        time.sleep(1)
        self.selenium.find_element(By.ID, "id_password").click()
        time.sleep(1)
        self.selenium.find_element(By.ID, "id_password").send_keys("Medrano00!")
        time.sleep(1)
        self.selenium.find_element(By.XPATH, "/html/body/div/div/div/div/div/div/div/form/input[2]").click()
        time.sleep(2)
        self.selenium.find_element(By.XPATH, "/html/body/div/header/nav/div/div/ul/li[2]/a").click()
        time.sleep(2)
        self.selenium.find_element(By.XPATH, "/html/body/div/header/nav/div/div/ul/li[2]/ul/li[3]/a").click()
        time.sleep(2)
        self.selenium.find_element(By.XPATH, "/html/body/div/main/div/div/div[1]/div/div/a").click()
        time.sleep(2)
        self.selenium.find_element(By.XPATH, "/html/body/div/main/div/div/div/button[1]/a").click()
        time.sleep(2)
        self.selenium.find_element(By.XPATH, "/html/body/app-root/app-home/main-panel/main/section/left-panel/div/app-payment-select/div/div/button[1]").click()
        time.sleep(4)
        self.selenium.find_element(By.XPATH, "/html/body/app-root/app-home/main-panel/main/section/right-panel/app-debit/div/div/button").click()
        time.sleep(4)
        self.selenium.find_element(By.XPATH, "/html/body/app-root/app-home/main-panel/main/section/right-panel/app-debit/div/div/ul/li/button").click()
        time.sleep(4)
        self.selenium.find_element(By.XPATH, "/html/body/app-root/app-home/main-panel/main/section/right-panel/app-debit/form[1]/div/div/input").click()
        time.sleep(4)
        self.selenium.find_element(By.XPATH, "/html/body/app-root/app-home/main-panel/main/section/right-panel/app-debit/form[1]/div/div/input").send_keys("4051 8856 0044 6623")
        time.sleep(4)
        self.selenium.find_element(By.XPATH, "/html/body/app-root/app-home/main-panel/main/section/right-panel/app-debit/form[1]/button").click()
        time.sleep(4)
        self.selenium.find_element(By.XPATH, "/html/body/div/form/table/tbody/tr[7]/td/input").click()
        time.sleep(4)
        self.selenium.find_element(By.XPATH, "/html/body/div/form/table/tbody/tr[7]/td/input").send_keys("11.111.111-1")
        time.sleep(4)
        self.selenium.find_element(By.XPATH, "/html/body/div/form/table/tbody/tr[8]/td/input").click()
        time.sleep(4)
        self.selenium.find_element(By.XPATH, "/html/body/div/form/table/tbody/tr[8]/td/input").send_keys("123")
        time.sleep(4)
        self.selenium.find_element(By.XPATH, "/html/body/div/form/table/tbody/tr[9]/td/input[1]").click()
        time.sleep(4)
        self.selenium.find_element(By.XPATH, "/html/body/div/form/table/tbody/tr[4]/td/input").click()
        time.sleep(7)

    def test_g03(self):
            
        # Caso de prueba para probar integración de Transbank - Opción Rechazar

        self.selenium.get("http://localhost:8000/")
        time.sleep(1)
        self.selenium.find_element(By.ID, "id_username").click()
        time.sleep(1)
        self.selenium.find_element(By.ID, "id_username").send_keys("asdasd")
        time.sleep(1)
        self.selenium.find_element(By.ID, "id_password").click()
        time.sleep(1)
        self.selenium.find_element(By.ID, "id_password").send_keys("Medrano00!")
        time.sleep(1)
        self.selenium.find_element(By.XPATH, "/html/body/div/div/div/div/div/div/div/form/input[2]").click()
        time.sleep(2)
        self.selenium.find_element(By.XPATH, "/html/body/div/header/nav/div/div/ul/li[2]/a").click()
        time.sleep(2)
        self.selenium.find_element(By.XPATH, "/html/body/div/header/nav/div/div/ul/li[2]/ul/li[3]/a").click()
        time.sleep(2)
        self.selenium.find_element(By.XPATH, "/html/body/div/main/div/div/div[1]/div/div/a").click()
        time.sleep(2)
        self.selenium.find_element(By.XPATH, "/html/body/div/main/div/div/div/button[1]/a").click()
        time.sleep(2)
        self.selenium.find_element(By.XPATH, "/html/body/app-root/app-home/main-panel/main/section/left-panel/div/app-payment-select/div/div/button[1]").click()
        time.sleep(4)
        self.selenium.find_element(By.XPATH, "/html/body/app-root/app-home/main-panel/main/section/right-panel/app-debit/div/div/button").click()
        time.sleep(4)
        self.selenium.find_element(By.XPATH, "/html/body/app-root/app-home/main-panel/main/section/right-panel/app-debit/div/div/ul/li/button").click()
        time.sleep(4)
        self.selenium.find_element(By.XPATH, "/html/body/app-root/app-home/main-panel/main/section/right-panel/app-debit/form[1]/div/div/input").click()
        time.sleep(4)
        self.selenium.find_element(By.XPATH, "/html/body/app-root/app-home/main-panel/main/section/right-panel/app-debit/form[1]/div/div/input").send_keys("4051 8856 0044 6623")
        time.sleep(4)
        self.selenium.find_element(By.XPATH, "/html/body/app-root/app-home/main-panel/main/section/right-panel/app-debit/form[1]/button").click()
        time.sleep(4)
        self.selenium.find_element(By.XPATH, "/html/body/div/form/table/tbody/tr[7]/td/input").click()
        time.sleep(4)
        self.selenium.find_element(By.XPATH, "/html/body/div/form/table/tbody/tr[7]/td/input").send_keys("11.111.111-1")
        time.sleep(4)
        self.selenium.find_element(By.XPATH, "/html/body/div/form/table/tbody/tr[8]/td/input").click()
        time.sleep(4)
        self.selenium.find_element(By.XPATH, "/html/body/div/form/table/tbody/tr[8]/td/input").send_keys("123")
        time.sleep(4)
        self.selenium.find_element(By.XPATH, "/html/body/div/form/table/tbody/tr[9]/td/input[1]").click()
        time.sleep(4)
        self.selenium.find_element(By.XPATH, "/html/body/div/form/table/tbody/tr[3]/td/select").click()
        time.sleep(4)
        self.selenium.find_element(By.XPATH, "/html/body/div/form/table/tbody/tr[3]/td/select/option[2]").click()
        time.sleep(4)
        self.selenium.find_element(By.XPATH, "/html/body/div/form/table").click()
        time.sleep(4)
        self.selenium.find_element(By.XPATH, "/html/body/div/form/table/tbody/tr[4]/td/input").click()
        time.sleep(7)

    def test_g04(self):

        # Caso de prueba para probar API de Banco Central

        self.selenium.get("http://localhost:8000/")
        time.sleep(1)
        self.selenium.find_element(By.ID, "id_username").click()
        time.sleep(1)
        self.selenium.find_element(By.ID, "id_username").send_keys("asdasd")
        time.sleep(1)
        self.selenium.find_element(By.ID, "id_password").click()
        time.sleep(1)
        self.selenium.find_element(By.ID, "id_password").send_keys("Medrano00!")
        time.sleep(1)
        self.selenium.find_element(By.XPATH, "/html/body/div/div/div/div/div/div/div/form/input[2]").click()
        time.sleep(3)
        self.selenium.find_element(By.XPATH, "/html/body/div/header/nav/div/div/ul/li[3]/a").click()
        time.sleep(3)
        self.selenium.find_element(By.XPATH, "/html/body/form/input[2]").click()
        time.sleep(3)
        self.selenium.find_element(By.XPATH, "/html/body/form/input[2]").send_keys("arica")
        time.sleep(3)
        self.selenium.find_element(By.XPATH, "/html/body/form/button").click()
        time.sleep(15)

    def test_g05(self):

        # Caso de prueba para probar ingresar un producto a la API propia de la página

        self.selenium.get("http://localhost:8000/")
        time.sleep(1)
        self.selenium.find_element(By.ID, "id_username").click()
        time.sleep(1)
        self.selenium.find_element(By.ID, "id_username").send_keys("asdasd")
        time.sleep(1)
        self.selenium.find_element(By.ID, "id_password").click()
        time.sleep(1)
        self.selenium.find_element(By.ID, "id_password").send_keys("Medrano00!")
        time.sleep(1)
        self.selenium.find_element(By.XPATH, "/html/body/div/div/div/div/div/div/div/form/input[2]").click()
        time.sleep(3)
        self.selenium.find_element(By.XPATH, "/html/body/div/header/nav/div/div/ul/li[4]/a").click()
        time.sleep(3)
        self.selenium.find_element(By.XPATH, "/html/body/div/div[2]/div/div[3]/div/div[1]/form/fieldset/div[1]/div/input").click()
        time.sleep(3)
        self.selenium.find_element(By.XPATH, "/html/body/div/div[2]/div/div[3]/div/div[1]/form/fieldset/div[1]/div/input").send_keys("Prueba1")
        time.sleep(3)
        self.selenium.find_element(By.XPATH, "/html/body/div/div[2]/div/div[3]/div/div[1]/form/fieldset/div[2]/div/input").click()
        time.sleep(3)
        self.selenium.find_element(By.XPATH, "/html/body/div/div[2]/div/div[3]/div/div[1]/form/fieldset/div[2]/div/input").send_keys("Bosch")
        time.sleep(3)
        self.selenium.find_element(By.XPATH, "/html/body/div/div[2]/div/div[3]/div/div[1]/form/fieldset/div[3]/div/input").click()
        time.sleep(3)
        self.selenium.find_element(By.XPATH, "/html/body/div/div[2]/div/div[3]/div/div[1]/form/fieldset/div[3]/div/input").send_keys("Prueba1")
        time.sleep(3)
        self.selenium.find_element(By.XPATH, "/html/body/div/div[2]/div/div[3]/div/div[1]/form/fieldset/div[4]/div/input").click()
        time.sleep(3)
        self.selenium.find_element(By.XPATH, "/html/body/div/div[2]/div/div[3]/div/div[1]/form/fieldset/div[4]/div/input").send_keys("Prueba 1")
        time.sleep(3)
        self.selenium.find_element(By.XPATH, "/html/body/div/div[2]/div/div[3]/div/div[1]/form/fieldset/div[5]/div/input").click()
        time.sleep(3)
        self.selenium.find_element(By.XPATH, "/html/body/div/div[2]/div/div[3]/div/div[1]/form/fieldset/div[5]/div/input").send_keys("29/05/2024 00:00")
        time.sleep(3)
        self.selenium.find_element(By.XPATH, "/html/body/div/div[2]/div/div[3]/div/div[1]/form/fieldset/div[6]/div/input").click()
        time.sleep(3)
        self.selenium.find_element(By.XPATH, "/html/body/div/div[2]/div/div[3]/div/div[1]/form/fieldset/div[6]/div/input").send_keys("3999990")
        time.sleep(3)
        self.selenium.find_element(By.XPATH, "/html/body/div/div[2]/div/div[3]/div/div[1]/form/fieldset/div[7]/button").click()
        time.sleep(5)

    def test_g06(self):

        # Caso de prueba para probar obtener todos los productos por medio de la API propia de la página

        self.selenium.get("http://localhost:8000/")
        time.sleep(1)
        self.selenium.find_element(By.ID, "id_username").click()
        time.sleep(1)
        self.selenium.find_element(By.ID, "id_username").send_keys("asdasd")
        time.sleep(1)
        self.selenium.find_element(By.ID, "id_password").click()
        time.sleep(1)
        self.selenium.find_element(By.ID, "id_password").send_keys("Medrano00!")
        time.sleep(1)
        self.selenium.find_element(By.XPATH, "/html/body/div/div/div/div/div/div/div/form/input[2]").click()
        time.sleep(3)
        self.selenium.find_element(By.XPATH, "/html/body/div/header/nav/div/div/ul/li[4]/a").click()
        time.sleep(3)
        self.selenium.find_element(By.XPATH, "/html/body/div/div[2]/div/div[1]/form[1]/fieldset/div/button").click()
        time.sleep(3)
        self.selenium.find_element(By.XPATH, "/html/body/div/div[2]/div/div[1]/form[1]/fieldset/div/ul/li[1]/a").click()
        time.sleep(5)

    def test_g07(self):

        # Caso de prueba para probar obtener el precio de la UF de los productos

        self.selenium.get("http://localhost:8000/")
        time.sleep(1)
        self.selenium.find_element(By.ID, "id_username").click()
        time.sleep(1)
        self.selenium.find_element(By.ID, "id_username").send_keys("asdasd")
        time.sleep(1)
        self.selenium.find_element(By.ID, "id_password").click()
        time.sleep(1)
        self.selenium.find_element(By.ID, "id_password").send_keys("Medrano00!")
        time.sleep(1)
        self.selenium.find_element(By.XPATH, "/html/body/div/div/div/div/div/div/div/form/input[2]").click()
        time.sleep(2)
        self.selenium.find_element(By.XPATH, "/html/body/div/header/nav/div/div/ul/li[2]/a").click()
        time.sleep(2)
        self.selenium.find_element(By.XPATH, "/html/body/div/header/nav/div/div/ul/li[2]/ul/li[3]/a").click()
        time.sleep(2)
        self.selenium.find_element(By.XPATH, "/html/body/div/main/div/div/div[1]/div/div/a").click()
        time.sleep(2)
        self.selenium.find_element(By.XPATH, "/html/body/div/main/div/div/div/button[2]").click()
        time.sleep(5)
